Limit flathubbot
This project seems require numpy version >=1.26.4

Prevent flathabbot checking higher versions 

See: https://github.com/flathub-infra/vorarbeiter/actions/runs/19606243386/job/56145564535

> ERROR: Could not find a version that satisfies the requirement numpy<2,>=1.26.4 (from pymol) (from versions: none)
> ERROR: No matching distribution found for numpy<2,>=1.26.4